### ISSUE TITLE
Feature To-Do list for v.1.0

### ISSUE THREAD

**Issue by seport** [seport/taskbit#4]
- [x] help section
- [ ] routine re-order
- [ ] floating action button which becomes "trash" when re-ordering to replace delete button
- [ ] make tasks editable
- [ ] time input formatting
- [ ] replace browser default popups with something else
- [ ] settings: delete all routines and import/export routines
